version: '3.8'

services:
  # Multi-Lingua app
  multi-lingua:
    image: ${DOCKER_IMAGE:-registry.gertrun.synology.me/multi-lingua:latest}
    platform: linux/amd64
    container_name: multi-lingua
    ports:
      - "3456:3456"
    environment:
      - NODE_ENV=production
      - PORT=3456
      - HOSTNAME=0.0.0.0
      - DOCKER_COMPOSE=true
      - LIBRETRANSLATE_URL=https://libretranslate.gertrun.synology.me
    volumes:
      # Persist the SQLite database
      - ml-data:/app/data
    restart: unless-stopped
    networks:
      - multi-lingua-network

networks:
  multi-lingua-network:
    driver: bridge

volumes:
  # Multi-Lingua SQLite database storage
  ml-data:
    driver: local
